/**
 * POST /api/presentation -- Re-generate an HTML5 presentation for an existing run.
 *
 * Presentations are now generated by the pipeline (Phase 4: PRESENT) and
 * saved to public/decks/{runId}.html. This endpoint allows re-generation
 * if the presentation-system.md spec is updated.
 */

import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { present } from "@/lib/pipeline/present";
import type { PipelineEvent } from "@/lib/pipeline/types";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

function safeParseJson<T>(json: string | null, fallback: T): T {
  try { return JSON.parse(json ?? "null") ?? fallback; }
  catch { return fallback; }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { runId } = body;

    if (!runId) {
      return NextResponse.json({ error: "runId is required" }, { status: 400 });
    }

    // Load run data from database
    const run = await db.run.findUniqueWithRelations(runId);

    if (!run) {
      return NextResponse.json({ error: "Run not found" }, { status: 404 });
    }

    const dimensions = run.dimensions ?? [];
    const agents = run.agents ?? [];
    const synthesisList = run.synthesis ?? [];

    const blueprint = {
      query: run.query,
      dimensions: dimensions.map((d) => ({
        name: d.name,
        description: d.description,
        justification: "",
        dataSources: [] as string[],
        lens: "",
        signalMatch: "",
      })),
      agents: agents.map((a) => ({
        name: a.name,
        archetype: a.archetype ?? "",
        dimension: a.dimension ?? "",
        mandate: a.mandate ?? "",
        tools: safeParseJson<string[]>(a.tools, []),
        lens: "",
        bias: "",
      })),
      interconnections: [] as { dimensionA: string; dimensionB: string; coupling: number; mechanism: string }[],
      complexityScore: {
        breadth: run.breadth ?? 3,
        depth: run.depth ?? 3,
        interconnection: run.interconnection ?? 3,
        total: run.complexityScore ?? 9,
        urgency: 1.0,
        adjusted: run.complexityScore ?? 9,
        reasoning: "",
      },
      tier: (run.tier ?? "STANDARD") as "MICRO" | "STANDARD" | "EXTENDED" | "MEGA" | "CAMPAIGN",
      estimatedTime: run.estimatedTime ?? "",
      ethicalConcerns: [] as string[],
    };

    const agentResults = agents.map((a) => ({
      agentName: a.name,
      archetype: a.archetype ?? "",
      dimension: a.dimension ?? "",
      findings: (a.findings ?? []).map((f) => ({
        statement: f.statement,
        evidence: f.evidence ?? "",
        confidence: (f.confidence ?? "MEDIUM") as "HIGH" | "MEDIUM" | "LOW",
        sourceTier: (f.sourceTier ?? "SECONDARY") as "PRIMARY" | "SECONDARY" | "TERTIARY",
        evidenceType: (f.evidenceType ?? "inferred") as "direct" | "inferred" | "analogical" | "modeled",
        source: f.source ?? "",
        implication: f.implication ?? "",
        tags: safeParseJson<string[]>(f.tags, []),
      })),
      gaps: [] as string[],
      signals: [] as string[],
      minorityViews: [] as string[],
      toolsUsed: safeParseJson<string[]>(a.tools, []),
      tokensUsed: 0,
    }));

    const synthesis = {
      layers: synthesisList.map((s) => ({
        name: s.layerName as "foundation" | "convergence" | "tension" | "emergence" | "gap",
        description: s.description,
        insights: safeParseJson<string[]>(s.insights, []),
      })),
      emergentInsights: [] as never[],
      tensionPoints: [] as never[],
      overallConfidence: "MEDIUM" as const,
      criticRevisions: [] as string[],
    };

    const events: PipelineEvent[] = [];
    const presentation = await present({
      synthesis,
      agentResults,
      blueprint,
      emitEvent: (e) => events.push(e),
    });

    // Save to public/decks/
    const decksDir = join(process.cwd(), "public", "decks");
    mkdirSync(decksDir, { recursive: true });
    const filename = `${runId}.html`;
    writeFileSync(join(decksDir, filename), presentation.html, "utf-8");

    // Upsert presentation record
    await db.presentation.upsertByRunId(runId, {
      title: presentation.title,
      subtitle: presentation.subtitle,
      htmlPath: `/decks/${filename}`,
      slideCount: presentation.slideCount,
    });

    return NextResponse.json({
      success: true,
      title: presentation.title,
      slideCount: presentation.slideCount,
      htmlPath: `/decks/${filename}`,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
